export const USER_LOGIN = "user_login";
export const USER_REGISTER = "user_register";
export const LOAD_USER = 'load_usr';
export const LOGOUT = 'logout';
export const CREATE_CUSTOMER="create_custoerm";
export const EDIT_CUSTOMER = "editcustomer";
export const FETCHS_CUSTOMER="fetchscustomer";
export const DELETE_CUSTOMER ="delete_customer";
export const SEARCH_CUSTOMER = "search_cusotmer"